// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVTfheVsVxFY6GAJb0E07YYNu4fUy6hg',
    appId: '1:349046656054:web:169fc8984b875c50e99c97',
    messagingSenderId: '349046656054',
    projectId: 'jigeen-7fad2',
    authDomain: 'jigeen-7fad2.firebaseapp.com',
    storageBucket: 'jigeen-7fad2.firebasestorage.app',
    measurementId: 'G-T8P0VRKR8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF7PWklD0TLSux3xoUZsMhTOk9zo_KSoQ',
    appId: '1:349046656054:android:6023d25ff19ba3e5e99c97',
    messagingSenderId: '349046656054',
    projectId: 'jigeen-7fad2',
    storageBucket: 'jigeen-7fad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0JqC63VH2rqRCjEQjfMmtZxNfa-_MviU',
    appId: '1:349046656054:ios:f0ce4f56ed496a2ae99c97',
    messagingSenderId: '349046656054',
    projectId: 'jigeen-7fad2',
    storageBucket: 'jigeen-7fad2.firebasestorage.app',
    iosBundleId: 'com.example.jigeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0JqC63VH2rqRCjEQjfMmtZxNfa-_MviU',
    appId: '1:349046656054:ios:f0ce4f56ed496a2ae99c97',
    messagingSenderId: '349046656054',
    projectId: 'jigeen-7fad2',
    storageBucket: 'jigeen-7fad2.firebasestorage.app',
    iosBundleId: 'com.example.jigeen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpVTfheVsVxFY6GAJb0E07YYNu4fUy6hg',
    appId: '1:349046656054:web:836955f57448be37e99c97',
    messagingSenderId: '349046656054',
    projectId: 'jigeen-7fad2',
    authDomain: 'jigeen-7fad2.firebaseapp.com',
    storageBucket: 'jigeen-7fad2.firebasestorage.app',
    measurementId: 'G-F44V2EXRX6',
  );
}
